### ISSUE TITLE
Geocoder CLI supprt

### ISSUE THREAD

**Issue by eyeseast** [eyeseast/geocode-sqlite#1]
Here are the geocoders currently supported by the CLI. I want to add the most common ones (which I use) first:

- [x] Google
- [x] MapBox
- [x] OpenStreetMap
- [x] MapQuest
- [x] Bing
- [ ] Geocode.Earth
- [ ] Geocodio
- [ ] Pelias
- [ ] MapTiler

What else?

**Comment by freyfogle** [comment]
OpenCage https://opencagedata.com/
